name: Lint PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: hotdog-werx/releez@v1
        with:
          mode: validate-commit
          commit-message: ${{ github.event.pull_request.title }}
